-- Phase 2C.2 — generic multi-course progress layer (IDEMPOTENT).
-- Re-runnable in the Supabase SQL Editor. Safe to paste again; no data loss.
-- Depends on: 001 (user_role(), touch_updated_at()) must be applied first.
--
-- WHY a NEW generic layer (not the Chinese tables):
--   The Chinese course keeps its bespoke tables (lesson_progress, voice_attempts,
--   phrase_progress) + cert/leaderboard pipeline UNTOUCHED. New courses (English
--   first) use these course-scoped tables keyed by (user_id, course_id, ...).
--   No Chinese migration, no destructive change.
--
-- What this adds:
--   - course_phrases        : reference table (course_id, lesson_id, phrase_id),
--                             seeded from lib/englishCourse.ts. RPCs validate
--                             phrase/lesson existence against THIS table.
--   - course_phrase_progress: per-user phrase "learned".
--   - course_voice_attempts : per-user English voice attempts (metadata only —
--                             NO transcript stored; privacy-preserving).
--   - course_quiz_attempts  : per-user English quiz attempts (append-only).
--   - course_lesson_progress: per-user lesson completion.
--   - FORCE RLS on all: staff = own rows only; manager = read all. No public.
--   - 4 SECURITY DEFINER RPCs (server is source of truth; direct writes revoked).
--
-- SECURITY MODEL:
--   - Tables grant SELECT only to authenticated; INSERT/UPDATE/DELETE are NOT
--     granted. All writes flow through SECURITY DEFINER RPCs that hard-set
--     user_id = auth.uid(), so a caller can only ever write their OWN rows and
--     cannot forge another user's progress.
--   - RPCs validate course_id/lesson_id/phrase_id against course_phrases, the
--     result enum, score bounds and quiz totals.
--   - No service_role. No secrets.

-- ============================================================
-- 1. Reference table: course_phrases (read-only for staff)
-- ============================================================
create table if not exists public.course_phrases (
  course_id   text not null,
  lesson_id   text not null,
  phrase_id   text not null,
  updated_at  timestamptz not null default now(),
  primary key (course_id, phrase_id)
);
create index if not exists course_phrases_lesson_idx on public.course_phrases(course_id, lesson_id);

alter table public.course_phrases enable row level security;
alter table public.course_phrases force  row level security;

revoke all    on public.course_phrases from anon, authenticated;
grant  select on public.course_phrases to   authenticated;

drop policy if exists course_phrases_read on public.course_phrases;
create policy course_phrases_read on public.course_phrases
  for select to authenticated using (true);

-- Seed (UPSERT) — generated by scripts/gen-english-progress-seed.mjs from
-- lib/englishCourse.ts. 128 English phrases across 16 lessons.
insert into public.course_phrases (course_id, lesson_id, phrase_id) values
  ('english-sales', 'english_greeting_help', 'en_g_1'),
  ('english-sales', 'english_greeting_help', 'en_g_2'),
  ('english-sales', 'english_greeting_help', 'en_g_3'),
  ('english-sales', 'english_greeting_help', 'en_g_4'),
  ('english-sales', 'english_greeting_help', 'en_g_5'),
  ('english-sales', 'english_greeting_help', 'en_g_6'),
  ('english-sales', 'english_greeting_help', 'en_g_7'),
  ('english-sales', 'english_greeting_help', 'en_g_8'),
  ('english-sales', 'english_asking_needs', 'en_n_1'),
  ('english-sales', 'english_asking_needs', 'en_n_2'),
  ('english-sales', 'english_asking_needs', 'en_n_3'),
  ('english-sales', 'english_asking_needs', 'en_n_4'),
  ('english-sales', 'english_asking_needs', 'en_n_5'),
  ('english-sales', 'english_asking_needs', 'en_n_6'),
  ('english-sales', 'english_asking_needs', 'en_n_7'),
  ('english-sales', 'english_asking_needs', 'en_n_8'),
  ('english-sales', 'english_recommendation', 'en_r_1'),
  ('english-sales', 'english_recommendation', 'en_r_2'),
  ('english-sales', 'english_recommendation', 'en_r_3'),
  ('english-sales', 'english_recommendation', 'en_r_4'),
  ('english-sales', 'english_recommendation', 'en_r_5'),
  ('english-sales', 'english_recommendation', 'en_r_6'),
  ('english-sales', 'english_recommendation', 'en_r_7'),
  ('english-sales', 'english_recommendation', 'en_r_8'),
  ('english-sales', 'english_price_promotion', 'en_p_1'),
  ('english-sales', 'english_price_promotion', 'en_p_2'),
  ('english-sales', 'english_price_promotion', 'en_p_3'),
  ('english-sales', 'english_price_promotion', 'en_p_4'),
  ('english-sales', 'english_price_promotion', 'en_p_5'),
  ('english-sales', 'english_price_promotion', 'en_p_6'),
  ('english-sales', 'english_price_promotion', 'en_p_7'),
  ('english-sales', 'english_price_promotion', 'en_p_8'),
  ('english-sales', 'english_payment_receipt', 'en_pay_1'),
  ('english-sales', 'english_payment_receipt', 'en_pay_2'),
  ('english-sales', 'english_payment_receipt', 'en_pay_3'),
  ('english-sales', 'english_payment_receipt', 'en_pay_4'),
  ('english-sales', 'english_payment_receipt', 'en_pay_5'),
  ('english-sales', 'english_payment_receipt', 'en_pay_6'),
  ('english-sales', 'english_payment_receipt', 'en_pay_7'),
  ('english-sales', 'english_payment_receipt', 'en_pay_8'),
  ('english-sales', 'english_polite_closing', 'en_c_1'),
  ('english-sales', 'english_polite_closing', 'en_c_2'),
  ('english-sales', 'english_polite_closing', 'en_c_3'),
  ('english-sales', 'english_polite_closing', 'en_c_4'),
  ('english-sales', 'english_polite_closing', 'en_c_5'),
  ('english-sales', 'english_polite_closing', 'en_c_6'),
  ('english-sales', 'english_polite_closing', 'en_c_7'),
  ('english-sales', 'english_polite_closing', 'en_c_8'),
  ('english-sales', 'english_perfume_sales', 'en_pf_1'),
  ('english-sales', 'english_perfume_sales', 'en_pf_2'),
  ('english-sales', 'english_perfume_sales', 'en_pf_3'),
  ('english-sales', 'english_perfume_sales', 'en_pf_4'),
  ('english-sales', 'english_perfume_sales', 'en_pf_5'),
  ('english-sales', 'english_perfume_sales', 'en_pf_6'),
  ('english-sales', 'english_perfume_sales', 'en_pf_7'),
  ('english-sales', 'english_perfume_sales', 'en_pf_8'),
  ('english-sales', 'english_cosmetics_sales', 'en_cos_1'),
  ('english-sales', 'english_cosmetics_sales', 'en_cos_2'),
  ('english-sales', 'english_cosmetics_sales', 'en_cos_3'),
  ('english-sales', 'english_cosmetics_sales', 'en_cos_4'),
  ('english-sales', 'english_cosmetics_sales', 'en_cos_5'),
  ('english-sales', 'english_cosmetics_sales', 'en_cos_6'),
  ('english-sales', 'english_cosmetics_sales', 'en_cos_7'),
  ('english-sales', 'english_cosmetics_sales', 'en_cos_8'),
  ('english-sales', 'english_wine_spirits_sales', 'en_wine_1'),
  ('english-sales', 'english_wine_spirits_sales', 'en_wine_2'),
  ('english-sales', 'english_wine_spirits_sales', 'en_wine_3'),
  ('english-sales', 'english_wine_spirits_sales', 'en_wine_4'),
  ('english-sales', 'english_wine_spirits_sales', 'en_wine_5'),
  ('english-sales', 'english_wine_spirits_sales', 'en_wine_6'),
  ('english-sales', 'english_wine_spirits_sales', 'en_wine_7'),
  ('english-sales', 'english_wine_spirits_sales', 'en_wine_8'),
  ('english-sales', 'english_tobacco_sales', 'en_tob_1'),
  ('english-sales', 'english_tobacco_sales', 'en_tob_2'),
  ('english-sales', 'english_tobacco_sales', 'en_tob_3'),
  ('english-sales', 'english_tobacco_sales', 'en_tob_4'),
  ('english-sales', 'english_tobacco_sales', 'en_tob_5'),
  ('english-sales', 'english_tobacco_sales', 'en_tob_6'),
  ('english-sales', 'english_tobacco_sales', 'en_tob_7'),
  ('english-sales', 'english_tobacco_sales', 'en_tob_8'),
  ('english-sales', 'english_confectionery_sales', 'en_conf_1'),
  ('english-sales', 'english_confectionery_sales', 'en_conf_2'),
  ('english-sales', 'english_confectionery_sales', 'en_conf_3'),
  ('english-sales', 'english_confectionery_sales', 'en_conf_4'),
  ('english-sales', 'english_confectionery_sales', 'en_conf_5'),
  ('english-sales', 'english_confectionery_sales', 'en_conf_6'),
  ('english-sales', 'english_confectionery_sales', 'en_conf_7'),
  ('english-sales', 'english_confectionery_sales', 'en_conf_8'),
  ('english-sales', 'english_duty_free_allowance', 'en_df_1'),
  ('english-sales', 'english_duty_free_allowance', 'en_df_2'),
  ('english-sales', 'english_duty_free_allowance', 'en_df_3'),
  ('english-sales', 'english_duty_free_allowance', 'en_df_4'),
  ('english-sales', 'english_duty_free_allowance', 'en_df_5'),
  ('english-sales', 'english_duty_free_allowance', 'en_df_6'),
  ('english-sales', 'english_duty_free_allowance', 'en_df_7'),
  ('english-sales', 'english_duty_free_allowance', 'en_df_8'),
  ('english-sales', 'english_boarding_passport', 'en_board_1'),
  ('english-sales', 'english_boarding_passport', 'en_board_2'),
  ('english-sales', 'english_boarding_passport', 'en_board_3'),
  ('english-sales', 'english_boarding_passport', 'en_board_4'),
  ('english-sales', 'english_boarding_passport', 'en_board_5'),
  ('english-sales', 'english_boarding_passport', 'en_board_6'),
  ('english-sales', 'english_boarding_passport', 'en_board_7'),
  ('english-sales', 'english_boarding_passport', 'en_board_8'),
  ('english-sales', 'english_gate_flight_timing', 'en_gate_1'),
  ('english-sales', 'english_gate_flight_timing', 'en_gate_2'),
  ('english-sales', 'english_gate_flight_timing', 'en_gate_3'),
  ('english-sales', 'english_gate_flight_timing', 'en_gate_4'),
  ('english-sales', 'english_gate_flight_timing', 'en_gate_5'),
  ('english-sales', 'english_gate_flight_timing', 'en_gate_6'),
  ('english-sales', 'english_gate_flight_timing', 'en_gate_7'),
  ('english-sales', 'english_gate_flight_timing', 'en_gate_8'),
  ('english-sales', 'english_stock_alternative', 'en_stock_1'),
  ('english-sales', 'english_stock_alternative', 'en_stock_2'),
  ('english-sales', 'english_stock_alternative', 'en_stock_3'),
  ('english-sales', 'english_stock_alternative', 'en_stock_4'),
  ('english-sales', 'english_stock_alternative', 'en_stock_5'),
  ('english-sales', 'english_stock_alternative', 'en_stock_6'),
  ('english-sales', 'english_stock_alternative', 'en_stock_7'),
  ('english-sales', 'english_stock_alternative', 'en_stock_8'),
  ('english-sales', 'english_refund_escalation', 'en_refund_1'),
  ('english-sales', 'english_refund_escalation', 'en_refund_2'),
  ('english-sales', 'english_refund_escalation', 'en_refund_3'),
  ('english-sales', 'english_refund_escalation', 'en_refund_4'),
  ('english-sales', 'english_refund_escalation', 'en_refund_5'),
  ('english-sales', 'english_refund_escalation', 'en_refund_6'),
  ('english-sales', 'english_refund_escalation', 'en_refund_7'),
  ('english-sales', 'english_refund_escalation', 'en_refund_8')
on conflict (course_id, phrase_id) do update set
  lesson_id = excluded.lesson_id,
  updated_at = now();

-- Prune any phrase ids no longer present in content (reference rows only).
delete from public.course_phrases
 where course_id = 'english-sales'
   and phrase_id not in ('en_g_1', 'en_g_2', 'en_g_3', 'en_g_4', 'en_g_5', 'en_g_6', 'en_g_7', 'en_g_8', 'en_n_1', 'en_n_2', 'en_n_3', 'en_n_4', 'en_n_5', 'en_n_6', 'en_n_7', 'en_n_8', 'en_r_1', 'en_r_2', 'en_r_3', 'en_r_4', 'en_r_5', 'en_r_6', 'en_r_7', 'en_r_8', 'en_p_1', 'en_p_2', 'en_p_3', 'en_p_4', 'en_p_5', 'en_p_6', 'en_p_7', 'en_p_8', 'en_pay_1', 'en_pay_2', 'en_pay_3', 'en_pay_4', 'en_pay_5', 'en_pay_6', 'en_pay_7', 'en_pay_8', 'en_c_1', 'en_c_2', 'en_c_3', 'en_c_4', 'en_c_5', 'en_c_6', 'en_c_7', 'en_c_8', 'en_pf_1', 'en_pf_2', 'en_pf_3', 'en_pf_4', 'en_pf_5', 'en_pf_6', 'en_pf_7', 'en_pf_8', 'en_cos_1', 'en_cos_2', 'en_cos_3', 'en_cos_4', 'en_cos_5', 'en_cos_6', 'en_cos_7', 'en_cos_8', 'en_wine_1', 'en_wine_2', 'en_wine_3', 'en_wine_4', 'en_wine_5', 'en_wine_6', 'en_wine_7', 'en_wine_8', 'en_tob_1', 'en_tob_2', 'en_tob_3', 'en_tob_4', 'en_tob_5', 'en_tob_6', 'en_tob_7', 'en_tob_8', 'en_conf_1', 'en_conf_2', 'en_conf_3', 'en_conf_4', 'en_conf_5', 'en_conf_6', 'en_conf_7', 'en_conf_8', 'en_df_1', 'en_df_2', 'en_df_3', 'en_df_4', 'en_df_5', 'en_df_6', 'en_df_7', 'en_df_8', 'en_board_1', 'en_board_2', 'en_board_3', 'en_board_4', 'en_board_5', 'en_board_6', 'en_board_7', 'en_board_8', 'en_gate_1', 'en_gate_2', 'en_gate_3', 'en_gate_4', 'en_gate_5', 'en_gate_6', 'en_gate_7', 'en_gate_8', 'en_stock_1', 'en_stock_2', 'en_stock_3', 'en_stock_4', 'en_stock_5', 'en_stock_6', 'en_stock_7', 'en_stock_8', 'en_refund_1', 'en_refund_2', 'en_refund_3', 'en_refund_4', 'en_refund_5', 'en_refund_6', 'en_refund_7', 'en_refund_8');

-- ============================================================
-- 2. Progress tables
-- ============================================================
create table if not exists public.course_phrase_progress (
  id          uuid primary key default gen_random_uuid(),
  user_id     uuid not null references auth.users(id) on delete cascade,
  course_id   text not null,
  lesson_id   text not null,
  phrase_id   text not null,
  learned     boolean not null default false,
  learned_at  timestamptz,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now(),
  unique (user_id, course_id, lesson_id, phrase_id)
);
create index if not exists cpp_user_course_idx on public.course_phrase_progress(user_id, course_id);
create index if not exists cpp_user_lesson_idx on public.course_phrase_progress(user_id, course_id, lesson_id);

create table if not exists public.course_voice_attempts (
  id          uuid primary key default gen_random_uuid(),
  user_id     uuid not null references auth.users(id) on delete cascade,
  course_id   text not null,
  lesson_id   text not null,
  phrase_id   text not null,
  result      text not null check (result in ('pass','retry','manual')),
  score       int check (score is null or (score >= 0 and score <= 100)),
  created_at  timestamptz not null default now()
);
create index if not exists cva_user_course_idx on public.course_voice_attempts(user_id, course_id);
create index if not exists cva_user_phrase_idx on public.course_voice_attempts(user_id, course_id, phrase_id);

create table if not exists public.course_quiz_attempts (
  id          uuid primary key default gen_random_uuid(),
  user_id     uuid not null references auth.users(id) on delete cascade,
  course_id   text not null,
  lesson_id   text not null,
  score       int not null check (score >= 0),
  total       int not null check (total > 0),
  passed      boolean not null,
  created_at  timestamptz not null default now(),
  check (score <= total)
);
create index if not exists cqa_user_course_idx on public.course_quiz_attempts(user_id, course_id);

create table if not exists public.course_lesson_progress (
  id            uuid primary key default gen_random_uuid(),
  user_id       uuid not null references auth.users(id) on delete cascade,
  course_id     text not null,
  lesson_id     text not null,
  completed     boolean not null default false,
  completed_at  timestamptz,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now(),
  unique (user_id, course_id, lesson_id)
);
create index if not exists clp_user_course_idx on public.course_lesson_progress(user_id, course_id);

-- ============================================================
-- 3. RLS enable + force
-- ============================================================
alter table public.course_phrase_progress enable row level security;
alter table public.course_phrase_progress force  row level security;
alter table public.course_voice_attempts  enable row level security;
alter table public.course_voice_attempts  force  row level security;
alter table public.course_quiz_attempts   enable row level security;
alter table public.course_quiz_attempts   force  row level security;
alter table public.course_lesson_progress enable row level security;
alter table public.course_lesson_progress force  row level security;

-- ============================================================
-- 4. Grants — SELECT only. Writes go through SECURITY DEFINER RPCs.
-- ============================================================
revoke all    on public.course_phrase_progress from anon, authenticated;
grant  select on public.course_phrase_progress to   authenticated;
revoke all    on public.course_voice_attempts  from anon, authenticated;
grant  select on public.course_voice_attempts  to   authenticated;
revoke all    on public.course_quiz_attempts   from anon, authenticated;
grant  select on public.course_quiz_attempts   to   authenticated;
revoke all    on public.course_lesson_progress from anon, authenticated;
grant  select on public.course_lesson_progress to   authenticated;

-- ============================================================
-- 5. Policies — self-select + manager-select (OR-combined). No write policies
--    needed (no direct write grants); SECURITY DEFINER RPCs bypass RLS safely.
-- ============================================================
-- course_phrase_progress
drop policy if exists cpp_self_select    on public.course_phrase_progress;
drop policy if exists cpp_manager_select on public.course_phrase_progress;
create policy cpp_self_select on public.course_phrase_progress
  for select to authenticated using (user_id = auth.uid());
create policy cpp_manager_select on public.course_phrase_progress
  for select to authenticated using (public.user_role() = 'manager');

-- course_voice_attempts
drop policy if exists cva_self_select    on public.course_voice_attempts;
drop policy if exists cva_manager_select on public.course_voice_attempts;
create policy cva_self_select on public.course_voice_attempts
  for select to authenticated using (user_id = auth.uid());
create policy cva_manager_select on public.course_voice_attempts
  for select to authenticated using (public.user_role() = 'manager');

-- course_quiz_attempts
drop policy if exists cqa_self_select    on public.course_quiz_attempts;
drop policy if exists cqa_manager_select on public.course_quiz_attempts;
create policy cqa_self_select on public.course_quiz_attempts
  for select to authenticated using (user_id = auth.uid());
create policy cqa_manager_select on public.course_quiz_attempts
  for select to authenticated using (public.user_role() = 'manager');

-- course_lesson_progress
drop policy if exists clp_self_select    on public.course_lesson_progress;
drop policy if exists clp_manager_select on public.course_lesson_progress;
create policy clp_self_select on public.course_lesson_progress
  for select to authenticated using (user_id = auth.uid());
create policy clp_manager_select on public.course_lesson_progress
  for select to authenticated using (public.user_role() = 'manager');

-- ============================================================
-- 6. updated_at touch triggers (reuse public.touch_updated_at from 001)
-- ============================================================
drop trigger if exists cpp_touch_updated_at on public.course_phrase_progress;
create trigger cpp_touch_updated_at
  before update on public.course_phrase_progress
  for each row execute function public.touch_updated_at();

drop trigger if exists clp_touch_updated_at on public.course_lesson_progress;
create trigger clp_touch_updated_at
  before update on public.course_lesson_progress
  for each row execute function public.touch_updated_at();

-- ============================================================
-- 7. RPCs (SECURITY DEFINER — write own rows only, validated against catalog)
-- ============================================================

-- mark_course_phrase_learned: validates (course_id, phrase_id) in course_phrases
-- and that the supplied lesson matches. Upserts learned state.
create or replace function public.mark_course_phrase_learned(
  p_course_id text,
  p_lesson_id text,
  p_phrase_id text,
  p_learned   boolean default true
)
returns void
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  uid uuid := auth.uid();
  ref_lesson text;
begin
  if uid is null then raise exception 'not authenticated'; end if;

  select lesson_id into ref_lesson
    from public.course_phrases
   where course_id = p_course_id and phrase_id = p_phrase_id;
  if ref_lesson is null then
    raise exception 'unknown phrase: %/%', p_course_id, p_phrase_id using errcode = 'P0002';
  end if;
  if p_lesson_id is not null and p_lesson_id <> ref_lesson then
    raise exception 'phrase % not in lesson %', p_phrase_id, p_lesson_id using errcode = 'P0001';
  end if;

  insert into public.course_phrase_progress (user_id, course_id, lesson_id, phrase_id, learned, learned_at)
  values (uid, p_course_id, ref_lesson, p_phrase_id, p_learned, case when p_learned then now() else null end)
  on conflict (user_id, course_id, lesson_id, phrase_id) do update set
    learned    = excluded.learned,
    learned_at = case
                   when excluded.learned and course_phrase_progress.learned_at is null then now()
                   when not excluded.learned then null
                   else course_phrase_progress.learned_at
                 end,
    updated_at = now();
end;
$$;

-- submit_course_voice_attempt: append-only. Validates phrase, result enum, score
-- bounds. NO transcript is accepted or stored (privacy).
create or replace function public.submit_course_voice_attempt(
  p_course_id text,
  p_lesson_id text,
  p_phrase_id text,
  p_result    text,
  p_score     int default null
)
returns void
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  uid uuid := auth.uid();
  ref_lesson text;
begin
  if uid is null then raise exception 'not authenticated'; end if;
  if p_result not in ('pass','retry','manual') then
    raise exception 'invalid result: %', p_result;
  end if;
  if p_score is not null and (p_score < 0 or p_score > 100) then
    raise exception 'invalid score: %', p_score;
  end if;

  select lesson_id into ref_lesson
    from public.course_phrases
   where course_id = p_course_id and phrase_id = p_phrase_id;
  if ref_lesson is null then
    raise exception 'unknown phrase: %/%', p_course_id, p_phrase_id using errcode = 'P0002';
  end if;

  insert into public.course_voice_attempts (user_id, course_id, lesson_id, phrase_id, result, score)
  values (uid, p_course_id, ref_lesson, p_phrase_id, p_result, case when p_result = 'manual' then null else p_score end);
end;
$$;

-- submit_course_quiz_attempt: append-only. Server computes passed (>=70%).
create or replace function public.submit_course_quiz_attempt(
  p_course_id text,
  p_lesson_id text,
  p_correct   int,
  p_total     int
)
returns table(score int, total int, passed boolean)
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  uid uuid := auth.uid();
  lesson_exists boolean;
  did_pass boolean;
begin
  if uid is null then raise exception 'not authenticated'; end if;
  if p_total is null or p_total <= 0 then raise exception 'invalid total: %', p_total; end if;
  if p_correct is null or p_correct < 0 or p_correct > p_total then
    raise exception 'invalid correct: % of %', p_correct, p_total;
  end if;

  select exists(
    select 1 from public.course_phrases where course_id = p_course_id and lesson_id = p_lesson_id
  ) into lesson_exists;
  if not lesson_exists then
    raise exception 'unknown lesson: %/%', p_course_id, p_lesson_id using errcode = 'P0002';
  end if;

  did_pass := round((p_correct::numeric / p_total::numeric) * 100) >= 70;

  insert into public.course_quiz_attempts (user_id, course_id, lesson_id, score, total, passed)
  values (uid, p_course_id, p_lesson_id, p_correct, p_total, did_pass);

  submit_course_quiz_attempt.score  := p_correct;
  submit_course_quiz_attempt.total  := p_total;
  submit_course_quiz_attempt.passed := did_pass;
  return next;
end;
$$;

-- mark_course_lesson_complete: validates lesson; guards completion behind at
-- least one learned phrase in that lesson (light anti-forge). Upserts.
create or replace function public.mark_course_lesson_complete(
  p_course_id text,
  p_lesson_id text,
  p_completed boolean default true
)
returns void
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  uid uuid := auth.uid();
  lesson_exists boolean;
  has_learned boolean;
begin
  if uid is null then raise exception 'not authenticated'; end if;

  select exists(
    select 1 from public.course_phrases where course_id = p_course_id and lesson_id = p_lesson_id
  ) into lesson_exists;
  if not lesson_exists then
    raise exception 'unknown lesson: %/%', p_course_id, p_lesson_id using errcode = 'P0002';
  end if;

  if p_completed then
    select exists(
      select 1 from public.course_phrase_progress
       where user_id = uid and course_id = p_course_id and lesson_id = p_lesson_id and learned = true
    ) into has_learned;
    if not has_learned then
      raise exception 'cannot complete lesson with no learned phrases' using errcode = 'P0001';
    end if;
  end if;

  insert into public.course_lesson_progress (user_id, course_id, lesson_id, completed, completed_at)
  values (uid, p_course_id, p_lesson_id, p_completed, case when p_completed then now() else null end)
  on conflict (user_id, course_id, lesson_id) do update set
    completed    = excluded.completed,
    completed_at = case
                     when excluded.completed and course_lesson_progress.completed_at is null then now()
                     when not excluded.completed then null
                     else course_lesson_progress.completed_at
                   end,
    updated_at = now();
end;
$$;

-- Grants on RPCs (deny anon).
revoke all on function public.mark_course_phrase_learned(text, text, text, boolean) from public;
revoke all on function public.submit_course_voice_attempt(text, text, text, text, int) from public;
revoke all on function public.submit_course_quiz_attempt(text, text, int, int) from public;
revoke all on function public.mark_course_lesson_complete(text, text, boolean) from public;
grant execute on function public.mark_course_phrase_learned(text, text, text, boolean) to authenticated;
grant execute on function public.submit_course_voice_attempt(text, text, text, text, int) to authenticated;
grant execute on function public.submit_course_quiz_attempt(text, text, int, int) to authenticated;
grant execute on function public.mark_course_lesson_complete(text, text, boolean) to authenticated;

-- ============================================================
-- 8. Verify
-- ============================================================
select
  (select count(*) from public.course_phrases where course_id = 'english-sales')                          as english_phrases_seeded,
  (select count(distinct lesson_id) from public.course_phrases where course_id = 'english-sales')         as english_lessons,
  (select count(*) from public.course_phrase_progress)                                     as phrase_progress_rows,
  (select count(*) from public.course_voice_attempts)                                      as voice_rows,
  (select count(*) from public.course_quiz_attempts)                                       as quiz_rows,
  (select count(*) from public.course_lesson_progress)                                     as lesson_rows,
  (select count(*) from pg_proc
     where pronamespace = 'public'::regnamespace
       and proname in ('mark_course_phrase_learned','submit_course_voice_attempt',
                       'submit_course_quiz_attempt','mark_course_lesson_complete'))        as rpcs_created,
  (select count(*) from pg_policies where schemaname='public'
     and tablename in ('course_phrase_progress','course_voice_attempts',
                       'course_quiz_attempts','course_lesson_progress'))                   as policy_count,
  (select count(*) from information_schema.table_privileges
     where grantee='authenticated' and privilege_type='INSERT'
       and table_name in ('course_phrase_progress','course_voice_attempts',
                          'course_quiz_attempts','course_lesson_progress'))                as direct_insert_grants;
-- Expected: english_phrases_seeded=128, english_lessons=16, rpcs_created=4,
--           policy_count=8, direct_insert_grants=0.
