-- Phase 2D — seed the Korean course (course_id='korean-sales') into
-- public.course_phrases (IDEMPOTENT). Re-runnable in the Supabase SQL Editor.
--
-- Depends on: 005_course_progress.sql (the generic course-progress tables,
--   RLS, and the SECURITY DEFINER RPCs). Korean REUSES that layer verbatim —
--   this migration adds NO tables, RPCs, policies, or grants. It only registers
--   Korean phrase ids so the existing RPCs accept Korean writes.
--
-- Scope guard (unchanged by design):
--   - Korean is NOT included in the Hall of Fame / weekly leaderboard.
--   - Korean has NO certificate.
--   - Voice attempts store metadata only (result + optional score) — NO transcript.
--   - No service_role. No secrets.
--
-- Generated by scripts/gen-korean-progress-seed.mjs from lib/koreanCourse.ts.
-- 114 Korean phrases across 16 lessons.

insert into public.course_phrases (course_id, lesson_id, phrase_id) values
  ('korean-sales', 'ko_greeting_help', 'ko_g_1'),
  ('korean-sales', 'ko_greeting_help', 'ko_g_2'),
  ('korean-sales', 'ko_greeting_help', 'ko_g_3'),
  ('korean-sales', 'ko_greeting_help', 'ko_g_4'),
  ('korean-sales', 'ko_greeting_help', 'ko_g_5'),
  ('korean-sales', 'ko_greeting_help', 'ko_g_6'),
  ('korean-sales', 'ko_greeting_help', 'ko_g_7'),
  ('korean-sales', 'ko_greeting_help', 'ko_g_8'),
  ('korean-sales', 'ko_asking_needs', 'ko_n_1'),
  ('korean-sales', 'ko_asking_needs', 'ko_n_2'),
  ('korean-sales', 'ko_asking_needs', 'ko_n_3'),
  ('korean-sales', 'ko_asking_needs', 'ko_n_4'),
  ('korean-sales', 'ko_asking_needs', 'ko_n_5'),
  ('korean-sales', 'ko_asking_needs', 'ko_n_6'),
  ('korean-sales', 'ko_asking_needs', 'ko_n_7'),
  ('korean-sales', 'ko_recommendation', 'ko_r_1'),
  ('korean-sales', 'ko_recommendation', 'ko_r_2'),
  ('korean-sales', 'ko_recommendation', 'ko_r_3'),
  ('korean-sales', 'ko_recommendation', 'ko_r_4'),
  ('korean-sales', 'ko_recommendation', 'ko_r_5'),
  ('korean-sales', 'ko_recommendation', 'ko_r_6'),
  ('korean-sales', 'ko_recommendation', 'ko_r_7'),
  ('korean-sales', 'ko_price_promotion', 'ko_p_1'),
  ('korean-sales', 'ko_price_promotion', 'ko_p_2'),
  ('korean-sales', 'ko_price_promotion', 'ko_p_3'),
  ('korean-sales', 'ko_price_promotion', 'ko_p_4'),
  ('korean-sales', 'ko_price_promotion', 'ko_p_5'),
  ('korean-sales', 'ko_price_promotion', 'ko_p_6'),
  ('korean-sales', 'ko_price_promotion', 'ko_p_7'),
  ('korean-sales', 'ko_payment_receipt', 'ko_pay_1'),
  ('korean-sales', 'ko_payment_receipt', 'ko_pay_2'),
  ('korean-sales', 'ko_payment_receipt', 'ko_pay_3'),
  ('korean-sales', 'ko_payment_receipt', 'ko_pay_4'),
  ('korean-sales', 'ko_payment_receipt', 'ko_pay_5'),
  ('korean-sales', 'ko_payment_receipt', 'ko_pay_6'),
  ('korean-sales', 'ko_payment_receipt', 'ko_pay_7'),
  ('korean-sales', 'ko_polite_closing', 'ko_c_1'),
  ('korean-sales', 'ko_polite_closing', 'ko_c_2'),
  ('korean-sales', 'ko_polite_closing', 'ko_c_3'),
  ('korean-sales', 'ko_polite_closing', 'ko_c_4'),
  ('korean-sales', 'ko_polite_closing', 'ko_c_5'),
  ('korean-sales', 'ko_polite_closing', 'ko_c_6'),
  ('korean-sales', 'ko_polite_closing', 'ko_c_7'),
  ('korean-sales', 'ko_perfume_sales', 'ko_pf_1'),
  ('korean-sales', 'ko_perfume_sales', 'ko_pf_2'),
  ('korean-sales', 'ko_perfume_sales', 'ko_pf_3'),
  ('korean-sales', 'ko_perfume_sales', 'ko_pf_4'),
  ('korean-sales', 'ko_perfume_sales', 'ko_pf_5'),
  ('korean-sales', 'ko_perfume_sales', 'ko_pf_6'),
  ('korean-sales', 'ko_perfume_sales', 'ko_pf_7'),
  ('korean-sales', 'ko_cosmetics_sales', 'ko_cos_1'),
  ('korean-sales', 'ko_cosmetics_sales', 'ko_cos_2'),
  ('korean-sales', 'ko_cosmetics_sales', 'ko_cos_3'),
  ('korean-sales', 'ko_cosmetics_sales', 'ko_cos_4'),
  ('korean-sales', 'ko_cosmetics_sales', 'ko_cos_5'),
  ('korean-sales', 'ko_cosmetics_sales', 'ko_cos_6'),
  ('korean-sales', 'ko_cosmetics_sales', 'ko_cos_7'),
  ('korean-sales', 'ko_wine_spirits_sales', 'ko_wine_1'),
  ('korean-sales', 'ko_wine_spirits_sales', 'ko_wine_2'),
  ('korean-sales', 'ko_wine_spirits_sales', 'ko_wine_3'),
  ('korean-sales', 'ko_wine_spirits_sales', 'ko_wine_4'),
  ('korean-sales', 'ko_wine_spirits_sales', 'ko_wine_5'),
  ('korean-sales', 'ko_wine_spirits_sales', 'ko_wine_6'),
  ('korean-sales', 'ko_wine_spirits_sales', 'ko_wine_7'),
  ('korean-sales', 'ko_tobacco_sales', 'ko_tob_1'),
  ('korean-sales', 'ko_tobacco_sales', 'ko_tob_2'),
  ('korean-sales', 'ko_tobacco_sales', 'ko_tob_3'),
  ('korean-sales', 'ko_tobacco_sales', 'ko_tob_4'),
  ('korean-sales', 'ko_tobacco_sales', 'ko_tob_5'),
  ('korean-sales', 'ko_tobacco_sales', 'ko_tob_6'),
  ('korean-sales', 'ko_tobacco_sales', 'ko_tob_7'),
  ('korean-sales', 'ko_confectionery_sales', 'ko_conf_1'),
  ('korean-sales', 'ko_confectionery_sales', 'ko_conf_2'),
  ('korean-sales', 'ko_confectionery_sales', 'ko_conf_3'),
  ('korean-sales', 'ko_confectionery_sales', 'ko_conf_4'),
  ('korean-sales', 'ko_confectionery_sales', 'ko_conf_5'),
  ('korean-sales', 'ko_confectionery_sales', 'ko_conf_6'),
  ('korean-sales', 'ko_confectionery_sales', 'ko_conf_7'),
  ('korean-sales', 'ko_boarding_passport', 'ko_board_1'),
  ('korean-sales', 'ko_boarding_passport', 'ko_board_2'),
  ('korean-sales', 'ko_boarding_passport', 'ko_board_3'),
  ('korean-sales', 'ko_boarding_passport', 'ko_board_4'),
  ('korean-sales', 'ko_boarding_passport', 'ko_board_5'),
  ('korean-sales', 'ko_boarding_passport', 'ko_board_6'),
  ('korean-sales', 'ko_boarding_passport', 'ko_board_7'),
  ('korean-sales', 'ko_duty_free_allowance', 'ko_df_1'),
  ('korean-sales', 'ko_duty_free_allowance', 'ko_df_2'),
  ('korean-sales', 'ko_duty_free_allowance', 'ko_df_3'),
  ('korean-sales', 'ko_duty_free_allowance', 'ko_df_4'),
  ('korean-sales', 'ko_duty_free_allowance', 'ko_df_5'),
  ('korean-sales', 'ko_duty_free_allowance', 'ko_df_6'),
  ('korean-sales', 'ko_duty_free_allowance', 'ko_df_7'),
  ('korean-sales', 'ko_gate_flight_timing', 'ko_gate_1'),
  ('korean-sales', 'ko_gate_flight_timing', 'ko_gate_2'),
  ('korean-sales', 'ko_gate_flight_timing', 'ko_gate_3'),
  ('korean-sales', 'ko_gate_flight_timing', 'ko_gate_4'),
  ('korean-sales', 'ko_gate_flight_timing', 'ko_gate_5'),
  ('korean-sales', 'ko_gate_flight_timing', 'ko_gate_6'),
  ('korean-sales', 'ko_gate_flight_timing', 'ko_gate_7'),
  ('korean-sales', 'ko_stock_alternative', 'ko_stock_1'),
  ('korean-sales', 'ko_stock_alternative', 'ko_stock_2'),
  ('korean-sales', 'ko_stock_alternative', 'ko_stock_3'),
  ('korean-sales', 'ko_stock_alternative', 'ko_stock_4'),
  ('korean-sales', 'ko_stock_alternative', 'ko_stock_5'),
  ('korean-sales', 'ko_stock_alternative', 'ko_stock_6'),
  ('korean-sales', 'ko_stock_alternative', 'ko_stock_7'),
  ('korean-sales', 'ko_refund_escalation', 'ko_refund_1'),
  ('korean-sales', 'ko_refund_escalation', 'ko_refund_2'),
  ('korean-sales', 'ko_refund_escalation', 'ko_refund_3'),
  ('korean-sales', 'ko_refund_escalation', 'ko_refund_4'),
  ('korean-sales', 'ko_refund_escalation', 'ko_refund_5'),
  ('korean-sales', 'ko_refund_escalation', 'ko_refund_6'),
  ('korean-sales', 'ko_refund_escalation', 'ko_refund_7'),
  ('korean-sales', 'ko_refund_escalation', 'ko_refund_8')
on conflict (course_id, phrase_id) do update set
  lesson_id = excluded.lesson_id,
  updated_at = now();

-- Prune any Korean phrase ids no longer present in content (reference rows only).
delete from public.course_phrases
 where course_id = 'korean-sales'
   and phrase_id not in ('ko_g_1', 'ko_g_2', 'ko_g_3', 'ko_g_4', 'ko_g_5', 'ko_g_6', 'ko_g_7', 'ko_g_8', 'ko_n_1', 'ko_n_2', 'ko_n_3', 'ko_n_4', 'ko_n_5', 'ko_n_6', 'ko_n_7', 'ko_r_1', 'ko_r_2', 'ko_r_3', 'ko_r_4', 'ko_r_5', 'ko_r_6', 'ko_r_7', 'ko_p_1', 'ko_p_2', 'ko_p_3', 'ko_p_4', 'ko_p_5', 'ko_p_6', 'ko_p_7', 'ko_pay_1', 'ko_pay_2', 'ko_pay_3', 'ko_pay_4', 'ko_pay_5', 'ko_pay_6', 'ko_pay_7', 'ko_c_1', 'ko_c_2', 'ko_c_3', 'ko_c_4', 'ko_c_5', 'ko_c_6', 'ko_c_7', 'ko_pf_1', 'ko_pf_2', 'ko_pf_3', 'ko_pf_4', 'ko_pf_5', 'ko_pf_6', 'ko_pf_7', 'ko_cos_1', 'ko_cos_2', 'ko_cos_3', 'ko_cos_4', 'ko_cos_5', 'ko_cos_6', 'ko_cos_7', 'ko_wine_1', 'ko_wine_2', 'ko_wine_3', 'ko_wine_4', 'ko_wine_5', 'ko_wine_6', 'ko_wine_7', 'ko_tob_1', 'ko_tob_2', 'ko_tob_3', 'ko_tob_4', 'ko_tob_5', 'ko_tob_6', 'ko_tob_7', 'ko_conf_1', 'ko_conf_2', 'ko_conf_3', 'ko_conf_4', 'ko_conf_5', 'ko_conf_6', 'ko_conf_7', 'ko_board_1', 'ko_board_2', 'ko_board_3', 'ko_board_4', 'ko_board_5', 'ko_board_6', 'ko_board_7', 'ko_df_1', 'ko_df_2', 'ko_df_3', 'ko_df_4', 'ko_df_5', 'ko_df_6', 'ko_df_7', 'ko_gate_1', 'ko_gate_2', 'ko_gate_3', 'ko_gate_4', 'ko_gate_5', 'ko_gate_6', 'ko_gate_7', 'ko_stock_1', 'ko_stock_2', 'ko_stock_3', 'ko_stock_4', 'ko_stock_5', 'ko_stock_6', 'ko_stock_7', 'ko_refund_1', 'ko_refund_2', 'ko_refund_3', 'ko_refund_4', 'ko_refund_5', 'ko_refund_6', 'ko_refund_7', 'ko_refund_8');

-- Verify
select
  (select count(*) from public.course_phrases where course_id = 'korean-sales')                  as korean_phrases_seeded,
  (select count(distinct lesson_id) from public.course_phrases where course_id = 'korean-sales') as korean_lessons;
-- Expected: korean_phrases_seeded=114, korean_lessons=16.
