-- Phase 2E — ADDITIVE seed of the English Foundations module into
-- public.course_phrases (IDEMPOTENT). Re-runnable in the Supabase SQL Editor.
--
-- Depends on: 005_course_progress.sql (generic tables + RPCs already applied).
-- This ONLY adds the new foundation phrase ids — it does NOT prune, so the
-- existing sales-lesson seed from 005 is untouched. No new tables/RPCs/grants.
-- English stays out of the certificate flow; this is just the course-progress
-- catalog so the existing RPCs accept foundation writes.
--
-- Generated by scripts/gen-english-foundations-seed.mjs from lib/englishCourse.ts.
-- 42 English foundation phrases across 6 lessons.

insert into public.course_phrases (course_id, lesson_id, phrase_id) values
  ('english-sales', 'english_basics_greetings', 'en_bg_1'),
  ('english-sales', 'english_basics_greetings', 'en_bg_2'),
  ('english-sales', 'english_basics_greetings', 'en_bg_3'),
  ('english-sales', 'english_basics_greetings', 'en_bg_4'),
  ('english-sales', 'english_basics_greetings', 'en_bg_5'),
  ('english-sales', 'english_basics_greetings', 'en_bg_6'),
  ('english-sales', 'english_basics_greetings', 'en_bg_7'),
  ('english-sales', 'english_basics_pronouns', 'en_bp_1'),
  ('english-sales', 'english_basics_pronouns', 'en_bp_2'),
  ('english-sales', 'english_basics_pronouns', 'en_bp_3'),
  ('english-sales', 'english_basics_pronouns', 'en_bp_4'),
  ('english-sales', 'english_basics_pronouns', 'en_bp_5'),
  ('english-sales', 'english_basics_pronouns', 'en_bp_6'),
  ('english-sales', 'english_basics_pronouns', 'en_bp_7'),
  ('english-sales', 'english_basics_numbers', 'en_bn_1'),
  ('english-sales', 'english_basics_numbers', 'en_bn_2'),
  ('english-sales', 'english_basics_numbers', 'en_bn_3'),
  ('english-sales', 'english_basics_numbers', 'en_bn_4'),
  ('english-sales', 'english_basics_numbers', 'en_bn_5'),
  ('english-sales', 'english_basics_numbers', 'en_bn_6'),
  ('english-sales', 'english_basics_numbers', 'en_bn_7'),
  ('english-sales', 'english_basics_colors', 'en_bc_1'),
  ('english-sales', 'english_basics_colors', 'en_bc_2'),
  ('english-sales', 'english_basics_colors', 'en_bc_3'),
  ('english-sales', 'english_basics_colors', 'en_bc_4'),
  ('english-sales', 'english_basics_colors', 'en_bc_5'),
  ('english-sales', 'english_basics_colors', 'en_bc_6'),
  ('english-sales', 'english_basics_colors', 'en_bc_7'),
  ('english-sales', 'english_basics_time', 'en_bt_1'),
  ('english-sales', 'english_basics_time', 'en_bt_2'),
  ('english-sales', 'english_basics_time', 'en_bt_3'),
  ('english-sales', 'english_basics_time', 'en_bt_4'),
  ('english-sales', 'english_basics_time', 'en_bt_5'),
  ('english-sales', 'english_basics_time', 'en_bt_6'),
  ('english-sales', 'english_basics_time', 'en_bt_7'),
  ('english-sales', 'english_basics_directions', 'en_bd_1'),
  ('english-sales', 'english_basics_directions', 'en_bd_2'),
  ('english-sales', 'english_basics_directions', 'en_bd_3'),
  ('english-sales', 'english_basics_directions', 'en_bd_4'),
  ('english-sales', 'english_basics_directions', 'en_bd_5'),
  ('english-sales', 'english_basics_directions', 'en_bd_6'),
  ('english-sales', 'english_basics_directions', 'en_bd_7')
on conflict (course_id, phrase_id) do update set
  lesson_id = excluded.lesson_id,
  updated_at = now();

-- Verify
select
  (select count(*) from public.course_phrases where course_id = 'english-sales')                       as english_phrases_total,
  (select count(*) from public.course_phrases where course_id = 'english-sales' and lesson_id like 'english_basics_%') as foundation_phrases,
  (select count(distinct lesson_id) from public.course_phrases where course_id = 'english-sales')      as english_lessons_total;
-- Expected after 005 + 007: english_phrases_total=170, foundation_phrases=42, english_lessons_total=22.
